const data = [
  {
    key: '1',
    name: 'Project Proposal.pdf',
    type: 'PDF',
    size: '2.5 MB',
    modified: '2024-01-15',
    owner: 'John Doe',
    status: 'Active',
  },
  {
    key: '2',
    name: 'Design Mockups',
    type: 'Folder',
    size: '15.2 MB',
    modified: '2024-01-14',
    owner: 'Jane Smith',
    status: 'Active',
  },
  {
    key: '3',
    name: 'User Manual.docx',
    type: 'DOCX',
    size: '1.8 MB',
    modified: '2024-01-13',
    owner: 'Mike Johnson',
    status: 'Archived',
  },
  {
    key: '4',
    name: 'Code Repository',
    type: 'Folder',
    size: '45.7 MB',
    modified: '2024-01-12',
    owner: 'Sarah Wilson',
    status: 'Active',
  },
  {
    key: '5',
    name: 'Meeting Notes.txt',
    type: 'TXT',
    size: '0.5 MB',
    modified: '2024-01-11',
    owner: 'David Brown',
    status: 'Active',
  },
];